### ISSUE TITLE
Marque component is getting expanded horizontally

### ISSUE THREAD

**Issue by meinhoongagan** [meinhoongagan/CCA-SIH#3]
Solve The Issue Refer Given Image
![CCA MARQUE ISSUE](https://github.com/user-attachments/assets/2af3d422-f2ab-452c-94ad-2c67988a5cce)

**Comment by Devpatelgurjar** [comment]
The Marque component is basically a automated slider animation that's why the component is much greater than the view port width

**Comment by meinhoongagan** [comment]
Solved
